Service review + matching function
ach-ber/IWA-Backend pull request #11
Opened 2023-11-23 15:34 UTC by TeenaNuihau

2023-11-24 12:39 UTC, ocean-sicard-baux requested changes
Pourqoi CandidateDTO a un id alors que establishment, experience et job, reference, review DTO n’ont pas de champ ID ?

2023-11-24 12:39 UTC, ocean-sicard-baux commented on service-job/src/main/java/com/iwa/jobservice/matching/MatchingService.java
> +    public double getEvaluationValue(List<Evaluation> evaluations) {
est-ce que tu peux ajouter des commentaires sur cette fonctions et sur toutes les fonctions non-explicites (= non-getter/setter ou crud) ? j’ai pas trop compris ici par exemple pourquoi on retourne 4 s’il n’y a pas d’évaluation

2023-11-24 12:39 UTC, ocean-sicard-baux commented on service-job/src/main/java/com/iwa/jobservice/matching/Opinion.java
> +        switch (score) {
pareil ici typiquement un commentaire expliquant les résultats avec le système qui a mené à ces résultats serait bien.

même en ayant le système sous les yeux (5x - 8y=0 et 4y-6z=0) je sais plus à quoi ça correspond. je sais qu’on veut que tant de notes à 5 étoiles doit être équivalent à tant de notes à 4 étoiles par exemple mais il faudrait détailler

2023-11-24 12:39 UTC, ocean-sicard-baux commented on service-job/src/main/java/com/iwa/jobservice/matching/Review.java
> +            case 0:
pareil là je sais pas pourquoi *2

2023-11-24 12:39 UTC, ocean-sicard-baux commented on service-job/src/main/resources/application.properties
> +candidates.api.url=http://172.26.192.1:8303
ça marche pas avec localhost?

2023-11-24 13:41 UTC, TeenaNuihau commented
> Pourqoi CandidateDTO a un id alors que establishment, experience et job, reference, review DTO n’ont pas de champ ID ?

cela correspond aux fields dans fake_candidates.json

2023-11-24 13:52 UTC, TeenaNuihau commented on service-job/src/main/java/com/iwa/jobservice/matching/MatchingService.java
> +    public double getEvaluationValue(List<Evaluation> evaluations) {
done

2023-11-24 14:01 UTC, TeenaNuihau commented on service-job/src/main/java/com/iwa/jobservice/matching/Opinion.java
> +        switch (score) {
done

2023-11-24 14:03 UTC, TeenaNuihau commented on service-job/src/main/java/com/iwa/jobservice/matching/Review.java
> +            case 0:
done

2023-11-24 14:24 UTC, TeenaNuihau commented on service-job/src/main/resources/application.properties
> +candidates.api.url=http://172.26.192.1:8303
j'ai pas trouvé comment faire sans, et localhost ne fonctionne pas
j'ai rajouté un readme et changer la variable dans ce fichier

2023-11-25 09:42 UTC, ach-ber approved these changes

2023-11-25 09:43 UTC, merged